# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
      - workflow-test

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
      
      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Run Angular lint
        run: npm run lint

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Run unit tests (headless)
        run: npm run test:ci

      - name: Upload coverage (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage