# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
      - workflow-test

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
      
      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Run Angular lint
        run: npm run lint

      - name: Build Angular app
        run: npm run build -- --configuration production

      # ----------------------------
      # Unit tests (PLACEHOLDER)
      # ----------------------------
      # Uncomment after tests are set up and passing locally.
      # Requires a working "test" script (e.g., "ng test") and headless Chrome launcher.
      #
      # - name: Run unit tests (headless)
      #   run: npm test -- --watch=false --browsers=ChromeHeadless

      # ----------------------------------
      # End-to-end tests (PLACEHOLDER)
      # ----------------------------------
      # Uncomment if you have e2e configured (Cypress or Playwright).
      #
      # - name: E2E tests (Cypress)
      #   run: |
      #     npx cypress install
      #     npx cypress run
      #
      # - name: E2E tests (Playwright)
      #   run: |
      #     npx playwright install --with-deps
      #     npx playwright test